name: Deploy Next.js to EC2

on:
  push:
    branches:
      - master   # Runs when you push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # ---------------------------
      # 1) CHECKOUT CODE
      # ---------------------------
      - name: Checkout code
        uses: actions/checkout@v3

      # ---------------------------
      # 2) SETUP SSH
      # ---------------------------
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      # ---------------------------
      # 3) SYNC PROJECT TO EC2
      # ---------------------------
      - name: Upload project to EC2
        run: |
          rsync -avzr --delete \
          -e "ssh -o StrictHostKeyChecking=no" \
          ./ \
          deploy@${{ secrets.EC2_HOST }}:/home/deploy/app

      # ---------------------------
      # 4) BUILD + DEPLOY DOCKER ON EC2
      # ---------------------------
      - name: Run deployment on EC2
        run: |
          ssh -o StrictHostKeyChecking=no deploy@${{ secrets.EC2_HOST }} << 'EOF'

            cd /home/deploy/app

            echo "Stopping old container..."
            docker stop next_container || true
            docker rm next_container || true

            echo "Building new Docker image..."
            docker build -t next_app .

            echo "Starting container..."
            docker run -d -p 3000:3000 --name next_container next_app

          EOF